import { LibraryProvider } from "@/libraries/LibraryProvider";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import "../styles/index.css";
import { HTMLDom } from "./_components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface IRootLayoutProps extends PropsWithChildren {}

const RootLayout: React.FC<IRootLayoutProps> = ({ children }) => {
  return (
    <LibraryProvider>
      <HTMLDom>{children}</HTMLDom>
    </LibraryProvider>
  );
};

export default RootLayout;
